- name: Deploy Jellyseerr
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: jellyseerr
        namespace: "{{ app_namespace }}"
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: jellyseerr
        template:
          metadata:
            labels:
              app: jellyseerr
          spec:
            containers:
              - name: jellyseerr
                image: fallenbagel/jellyseerr
                ports:
                  - containerPort: 5055
                env:
                  - name: TZ
                    value: "Asia/Dhaka"
                volumeMounts:
                  - name: config
                    mountPath: /app/config
                    subPath: jellyseerr
            volumes:
              - name: config
                persistentVolumeClaim:
                  claimName: "{{ config_pvc_name }}"
  delegate_to: "{{ k8s_delegate }}"

- name: Create Jellyseerr service
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: jellyseerr
        namespace: "{{ app_namespace }}"
      spec:
        selector:
          app: jellyseerr
        ports:
          - protocol: TCP
            port: 5055
            targetPort: 5055
        type: LoadBalancer
  delegate_to: "{{ k8s_delegate }}"