- name: Delete Jellyseerr Deployment
  kubernetes.core.k8s:
    state: absent
    kind: Deployment
    name: jellyseerr
    namespace: "{{ app_namespace }}"

- name: Delete Jellyseerr Service
  kubernetes.core.k8s:
    state: absent
    kind: Service
    name: jellyseerr
    namespace: "{{ app_namespace }}"
