- name: Deploy Sonarr
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: sonarr
        namespace: "{{ app_namespace }}"
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: sonarr
        template:
          metadata:
            labels:
              app: sonarr
          spec:
            containers:
              - name: sonarr
                image: linuxserver/sonarr:4.0.15.2941-ls296
                ports:
                  - containerPort: 8989
                env:
                  - name: PUID
                    value: "1000"
                  - name: PGID
                    value: "1000"
                  - name: TZ
                    value: "{{ app_timezone }}"
                volumeMounts:
                  - name: config
                    mountPath: /config
                    subPath: sonarr
                  - name: media
                    mountPath: /movies
                    subPath: movies
                  - name: media
                    mountPath: /downloads
            volumes:
              - name: config
                persistentVolumeClaim:
                  claimName: "{{ config_pvc_name }}"
              - name: media
                persistentVolumeClaim:
                  claimName: "{{ media_pvc_name }}"
  delegate_to: "{{ k8s_delegate }}"

- name: Create Sonarr Service
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: sonarr
        namespace: "{{ app_namespace }}"
      spec:
        selector:
          app: sonarr
        ports:
          - name: web
            protocol: TCP
            port: 8989
            targetPort: 8989
        type: LoadBalancer
  delegate_to: "{{ k8s_delegate }}"