- name: Deploy Deluge
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: deluge
        namespace: "{{ app_namespace }}"
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: deluge
        template:
          metadata:
            labels:
              app: deluge
          spec:
            containers:
              - name: deluge
                image: linuxserver/deluge
                ports:
                  - containerPort: 8112
                env:
                  - name: PUID
                    value: "1000"
                  - name: PGID
                    value: "1000"
                  - name: TZ
                    value: "Asia/Dhaka"
                volumeMounts:
                  - name: config
                    mountPath: /config
                    subPath: deluge
                  - name: media
                    mountPath: /downloads
            volumes:
              - name: config
                persistentVolumeClaim:
                  claimName: "{{ config_pvc_name }}"
              - name: media
                persistentVolumeClaim:
                  claimName: "{{ media_pvc_name }}"

- name: Create Deluge Service
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: deluge
        namespace: "{{ app_namespace }}"
      spec:
        selector:
          app: deluge
        ports:
          - protocol: TCP
            port: 8112
            targetPort: 8112
            name: web
        type: LoadBalancer
