- name: Install Deluge
  kubernetes.core.helm:
    release_namespace: "{{ app_namespace }}"
    create_namespace: true
    name: deluge
    state: present
    chart_ref: deluge
    chart_repo_url: https://lib42.github.io/charts
    chart_version: 1.3.0
    values:
      service:
        main:
          type: LoadBalancer
      persistence:
        config:
          enabled: true
          mountPath: /config
          size: 10M
        downloads:
          enabled: true
          type: pvc
          existingClaim: "{{ shared_pvc_name }}"
          mountPath: /downloads