- name: Delete Deluge Deployment
  kubernetes.core.k8s:
    state: absent
    kind: Deployment
    name: deluge
    namespace: "{{ app_namespace }}"
  delegate_to: "{{ k8s_delegate }}"

- name: Delete Deluge Service
  kubernetes.core.k8s:
    state: absent
    kind: Service
    name: deluge
    namespace: "{{ app_namespace }}"
  delegate_to: "{{ k8s_delegate }}"
