- name: Delete Deluge Deployment
  kubernetes.core.k8s:
    state: absent
    kind: Deployment
    name: deluge
    namespace: "{{ app_namespace }}"

- name: Delete Deluge Service
  kubernetes.core.k8s:
    state: absent
    kind: Service
    name: deluge
    namespace: "{{ app_namespace }}"
