- name: Install HTPC apps
  hosts: cluster_nodes
  vars:
    app_namespace: htpc
    shared_pvc_name: htpc-shared-pvc
  roles:
    - role: volumes
    - role: helm
    - role: deluge
      vars:
        task: install
    - role: jellyfin
      vars:
        task: install
    - role: jellyseerr
      vars:
        task: install
    - role: radarr
      vars:
        task: install
    - role: jackett
      vars:
        task: install
