- name: Install HTPC apps
  hosts: cluster_nodes
  vars:
    app_namespace: htpc
    media_pvc_name: htpc-media
    config_pvc_name: htpc-config
    k8s_delegate: localhost
  roles:
    - role: volumes
    - role: jackett
      vars:
        task: install
    - role: radarr
      vars:
        task: install
    - role: deluge
      vars:
        task: install
    - role: jellyfin
      vars:
        task: install
    - role: jellyseerr
      vars:
        task: install
