- name: Uninstall HTPC apps
  hosts: cluster_nodes
  vars:
    app_namespace: htpc
  roles:
    - role: helm
    - role: deluge
      vars:
        task: uninstall
    - role: jellyfin
      vars:
        task: uninstall
  tasks:
    - name: Delete HTPC namespace
      ansible.builtin.shell: |
        kubectl delete namespace htpc
      args:
        executable: /bin/bash