- name: Uninstall HTPC apps
  hosts: cluster_nodes
  vars:
    app_namespace: htpc
  roles:
    - role: helm
    - role: deluge
      vars:
        task: uninstall
    - role: jellyfin
      vars:
        task: uninstall
  tasks:
    - name: Delete HTPC namespace
      kubernetes.core.k8s:
        state: absent
        namespace: "{{ app_namespace }}"
        kind: Namespace
