- name: Uninstall HTPC apps
  hosts: cluster_nodes
  vars:
    app_namespace: htpc
    k8s_delegate: localhost
  roles:
    - role: jackett
      vars:
        task: uninstall
    - role: radarr
      vars:
        task: uninstall
    - role: deluge
      vars:
        task: uninstall
    - role: jellyfin
      vars:
        task: uninstall
    - role: jellyseerr
      vars:
        task: uninstall
  tasks:
    - name: Delete HTPC namespace
      kubernetes.core.k8s:
        state: absent
        namespace: "{{ app_namespace }}"
        kind: Namespace
      delegate_to: "{{ k8s_delegate }}"
