- name: Ensure HTPC namespace exists
  kubernetes.core.k8s:
    state: present
    kind: Namespace
    name: "{{ app_namespace }}"

- name: Create shared PVC for Deluge and Jellyfin
  kubernetes.core.k8s:
    state: present
    namespace: "{{ app_namespace }}"
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: htpc-shared-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: local-path
