- name: Delete Radarr Deployment
  kubernetes.core.k8s:
    state: absent
    kind: Deployment
    name: radarr
    namespace: "{{ app_namespace }}"

- name: Delete Radarr Service
  kubernetes.core.k8s:
    state: absent
    kind: Service
    name: radarr
    namespace: "{{ app_namespace }}"
