- name: Delete Jackett Deployment
  kubernetes.core.k8s:
    state: absent
    kind: Deployment
    name: jackett
    namespace: "{{ app_namespace }}"
  delegate_to: "{{ k8s_delegate }}"

- name: Delete Jackett Service
  kubernetes.core.k8s:
    state: absent
    kind: Service
    name: jackett
    namespace: "{{ app_namespace }}"
  delegate_to: "{{ k8s_delegate }}"
