- name: Uninstall HTPC apps
  hosts: local
  vars:
    app_namespace: htpc
    media_pvc_name: htpc-media
    config_pvc_name: htpc-config
    k8s_delegate: localhost
  roles:
    - role: deluge
      vars:
        task: uninstall
    - role: jackett
      vars:
        task: uninstall
    - role: radarr
      vars:
        task: uninstall
    - role: sonarr
      vars:
        task: uninstall
    - role: jellyseerr
      vars:
        task: uninstall
    - role: jellyfin
      vars:
        task: uninstall
    - role: organizr
      vars:
        task: uninstall
    - role: volumes
      vars:
        task: uninstall
  tasks:
    - name: Delete HTPC namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: "{{ app_namespace }}"
        state: absent
      delegate_to: "{{ k8s_delegate }}"
