- name: Deploy Jellyfin
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: jellyfin
        namespace: "{{ app_namespace }}"
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: jellyfin
        template:
          metadata:
            labels:
              app: jellyfin
          spec:
            containers:
              - name: jellyfin
                image: linuxserver/jellyfin
                ports:
                  - containerPort: 8096
                env:
                  - name: PUID
                    value: "1000"
                  - name: PGID
                    value: "1000"
                  - name: TZ
                    value: "Asia/Dhaka"
                volumeMounts:
                  - name: config
                    mountPath: /config
                    subPath: jellyfin
                  - name: media
                    mountPath: /data
            volumes:
              - name: config
                persistentVolumeClaim:
                  claimName: "{{ config_pvc_name }}"
              - name: media
                persistentVolumeClaim:
                  claimName: "{{ media_pvc_name }}"

- name: Create Jellyfin Service
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: jellyfin
        namespace: "{{ app_namespace }}"
      spec:
        selector:
          app: jellyfin
        ports:
          - protocol: TCP
            port: 8096
            targetPort: 8096
        type: LoadBalancer
