- name: Install Jellyfin
  kubernetes.core.helm:
    release_namespace: "{{ app_namespace }}"
    create_namespace: true
    name: jellyfin
    state: present
    chart_ref: jellyfin
    chart_repo_url: https://djjudas21.github.io/charts/
    chart_version: 3.2.7
    values:
      service:
        type: LoadBalancer
      jellyfin:
        mediaVolumes:
          - name: tutorials
            readOnly: false
            existingClaim: "{{ shared_pvc_name }}"
