- name: Delete Jellyfin Deployment
  kubernetes.core.k8s:
    state: absent
    kind: Deployment
    name: jellyfin
    namespace: "{{ app_namespace }}"
  delegate_to: "{{ k8s_delegate }}"

- name: Delete Jellyfin Service
  kubernetes.core.k8s:
    state: absent
    kind: Service
    name: jellyfin
    namespace: "{{ app_namespace }}"
  delegate_to: "{{ k8s_delegate }}"
